import type { Task, ParaItem } from "../types/task"

export const defaultParaItems: ParaItem[] = [
  // Projects
  { id: "p1", name: "Funnel LT8", type: "project" },
  { id: "p2", name: "Funnel Hub + Newsletter", type: "project" },
  { id: "p3", name: "VSL", type: "project" },
  // Areas
  { id: "a1", name: "Marketing", type: "area" },
  { id: "a2", name: "Ventas", type: "area" },
  { id: "a3", name: "Producto", type: "area" },
  { id: "a4", name: "Operaciones", type: "area" },
  // Resources
  { id: "r1", name: "Brandkit", type: "resource" },
  { id: "r2", name: "SOPs", type: "resource" },
]

export const defaultTasks: Task[] = [
  // === COMPLETADAS ===
  {
    id: "t1",
    title: "Anadir seccion de claridad en la landing (que la persona entienda el flow completo)",
    description: "Que el visitante entienda claramente el flujo completo del producto.",
    status: "done",
    priority: "urgent",
    assignee: "marco",
    paraId: "p1",
    dueDate: "2026-04-10",
    createdAt: "2026-04-10T08:00:00Z",
    completedAt: "2026-04-11T10:00:00Z",
  },
  {
    id: "t2",
    title: "Anadir seccion de cinturones/niveles (estilo teaser, que genere curiosidad)",
    description: "Seccion visual tipo gamificacion con niveles/cinturones para generar curiosidad.",
    status: "done",
    priority: "urgent",
    assignee: "marco",
    paraId: "p1",
    dueDate: "2026-04-10",
    createdAt: "2026-04-10T08:05:00Z",
    completedAt: "2026-04-11T10:00:00Z",
  },
  {
    id: "t4",
    title: "Montar Funnel Hub + Newsletter",
    description: "Crear el funnel de captacion con hub de contenido y sistema de newsletter.",
    status: "done",
    priority: "high",
    assignee: "marco",
    paraId: "p2",
    dueDate: "2026-04-13",
    createdAt: "2026-04-10T08:15:00Z",
    completedAt: "2026-04-11T10:00:00Z",
  },
  // === ACTIVAS ===
  {
    id: "t3",
    title: "Esperar 3 dias para metricas solidas de la VSL en PandaVideo",
    description: "Esperar a tener datos suficientes antes de tomar decisiones sobre la VSL.",
    status: "waiting",
    priority: "high",
    assignee: "equipo",
    paraId: "p3",
    dueDate: "2026-04-13",
    createdAt: "2026-04-10T08:10:00Z",
    completedAt: null,
  },
  {
    id: "t5",
    title: "Nuevos anuncios con el enfoque de JP (analisis + formacion + empleo)",
    description: "Crear nuevas creatividades publicitarias con el angulo de analisis + formacion + empleo.",
    status: "next",
    priority: "normal",
    assignee: "marco",
    paraId: "a1",
    dueDate: "2026-04-17",
    createdAt: "2026-04-10T08:20:00Z",
    completedAt: null,
  },
  {
    id: "t6",
    title: "Si VSL no cumple KPIs -> grabar nueva VSL de 3-4 min",
    description: "Contingencia: si las metricas de la VSL actual no cumplen, grabar una nueva version mas corta.",
    status: "someday",
    priority: "normal",
    assignee: "equipo",
    paraId: "p3",
    dueDate: null,
    createdAt: "2026-04-10T08:25:00Z",
    completedAt: null,
  },
  // === NUEVAS ===
  {
    id: "t7",
    title: "Crear pagina de gracias del Funnel Hub (post-registro formulario)",
    description: "Cuando alguien se registra en el formulario del Funnel Hub, redirigir a una pagina de gracias.",
    status: "done",
    priority: "high",
    assignee: "marco",
    paraId: "p2",
    dueDate: null,
    createdAt: "2026-04-11T10:00:00Z",
    completedAt: "2026-04-11T12:00:00Z",
  },
  {
    id: "t8",
    title: "Crear formulario de Busco Talento Digital",
    description: "Formulario para empresas que buscan contratar talento digital certificado por Capital Hub.",
    status: "next",
    priority: "high",
    assignee: "marco",
    paraId: "p2",
    dueDate: null,
    createdAt: "2026-04-11T10:05:00Z",
    completedAt: null,
  },
  {
    id: "t9",
    title: "Anadir link en seccion Quiero una Carrera Digital — Empezar hoy",
    description: "Conectar el CTA de la seccion con el destino correcto.",
    status: "next",
    priority: "normal",
    assignee: "marco",
    paraId: "p2",
    dueDate: null,
    createdAt: "2026-04-11T10:10:00Z",
    completedAt: null,
  },
  {
    id: "t10",
    title: "Anadir links en footer: terminos, privacidad y login",
    description: "Conectar los links del footer a las paginas correspondientes de terminos de uso, politica de privacidad y login.",
    status: "next",
    priority: "normal",
    assignee: "marco",
    paraId: "p2",
    dueDate: null,
    createdAt: "2026-04-11T10:15:00Z",
    completedAt: null,
  },
  {
    id: "t12",
    title: "Cambiar dominio con Adrian",
    description: "Coordinar con Adrian el cambio de dominio.",
    status: "next",
    priority: "high",
    assignee: "equipo",
    paraId: "p2",
    dueDate: null,
    createdAt: "2026-04-11T12:05:00Z",
    completedAt: null,
  },
  {
    id: "t11",
    title: "Anadir API de conversion al formulario de Funnel Hub y a la automatizacion",
    description: "Integrar la API de conversion (CAPI) tanto en el formulario del Funnel Hub como en la automatizacion asociada.",
    status: "next",
    priority: "high",
    assignee: "marco",
    paraId: "p2",
    dueDate: null,
    createdAt: "2026-04-11T12:00:00Z",
    completedAt: null,
  },
  {
    id: "t_ghl_oauth_v2",
    title: "Integrar GHL API v2 (OAuth 2.0) para control total de GoHighLevel",
    description: "Sustituir la conexion actual de GHL por API Key (v1) por un flujo OAuth 2.0 con v2 para tener acceso total a todos los recursos de GHL (read+write en contactos, pipelines, conversaciones, calendarios, campanas, workflows, tags, custom fields, payments, invoices, productos, funnels y multi-location).\n\nPasos:\n1. Crear cuenta developer en https://marketplace.gohighlevel.com/ (o iniciar sesion si ya existe).\n2. En Developer Portal -> My Apps -> Create App. Datos: APP Name 'Capital Hub OS', Target User 'Sub-account', Distribution 'Both Agency & Sub-account'.\n3. En Advanced Settings -> Auth configurar:\n   - Redirect URI: https://ecoai.capitalhubapp.com/api/auth/ghl/callback (+ http://localhost:3000/api/auth/ghl/callback para desarrollo local).\n   - Scopes: TODOS los disponibles para tener control total (contacts.*, conversations.*, opportunities.*, calendars.*, campaigns.*, workflows.*, locations.*, users.*, custom-fields.*, tags.*, notes.*, tasks.*, payments.*, invoices.*, products.*, funnels.*, medias.*, forms.*, surveys.*).\n4. Guardar Client ID y Client Secret en Vercel (envs: GHL_CLIENT_ID, GHL_CLIENT_SECRET) y en .env.local.\n5. En codigo:\n   - Nueva server action: iniciar flujo OAuth (redirige a https://marketplace.gohighlevel.com/oauth/chooselocation con params).\n   - Nueva route handler: /api/auth/ghl/callback que intercambia code por access_token + refresh_token, guarda en api_connections con credentials jsonb.\n   - Migrar ghl-adapter: quitar API Key v1, usar access_token con auto-refresh (Bearer Authorization). Endpoints base: https://services.leadconnectorhq.com/.\n   - Reemplazar el formulario manual de Connect GHL en /integrations por boton 'Conectar con GHL' que dispara el OAuth.\n6. Validar con Playwright: login, conectar GHL, ver metricas reales en dashboard (CRM tab).\n\nDocs oficiales:\n- Getting started: https://help.gohighlevel.com/support/solutions/articles/155000000136\n- Create app: https://marketplace.gohighlevel.com/docs/oauth/CreateMarketplaceApp\n- OAuth 2.0: https://marketplace.gohighlevel.com/docs/Authorization/OAuth2.0/index.html\n- API Reference: https://marketplace.gohighlevel.com/docs/",
    status: "someday",
    priority: "normal",
    assignee: "equipo",
    paraId: "a4",
    dueDate: null,
    createdAt: "2026-04-18T08:50:00Z",
    completedAt: null,
  },
  {
    id: "t_pwa_push_migration",
    title: "Aplicar migracion 0006_push_notifications en Supabase de Capital Hub",
    description: "La migracion de push notifications ya esta en supabase/migrations/0006_push_notifications.sql pero aun NO se aplico al proyecto Supabase real de Capital Hub (por error se aplico en otro proyecto; ya revisado). Hay que aplicarla en el Supabase correcto + anadir las VAPID keys en Vercel.\n\nPasos:\n1. Abrir el proyecto Supabase de Capital Hub (cuenta de Adrian u org compartida — NO nvision-saas).\n2. Dashboard > SQL Editor > pegar el contenido de supabase/migrations/0006_push_notifications.sql y ejecutar. Crea tablas push_subscriptions y notifications + RLS.\n3. Verificar en Table Editor que aparecen push_subscriptions (0 rows) y notifications (0 rows) con RLS habilitado.\n4. Anadir 4 env vars en Vercel (Production, Preview, Development):\n   - NEXT_PUBLIC_VAPID_PUBLIC_KEY: BBSaiwqrgZl-LoEC1pjf3Zg1xOWmdXcDRS1xJIN6yN8awAzUh2PEULkPKGhjY9PvUctfz_ifwUWqThSXNDhXxJg\n   - VAPID_PRIVATE_KEY: V_WRmvFs5caKX-VTAIgVPmamOiDEvirDu6khAnou5NM\n   - VAPID_SUBJECT: mailto:marcoapereirav@gmail.com\n   - SUPABASE_SERVICE_ROLE_KEY: copiarla del dashboard Supabase de Capital Hub > Settings > API > service_role (secret).\n5. Redeploy en Vercel (Deployments > ultimo deploy > Redeploy, desmarcar Use existing Build Cache).\n6. Probar: entrar a ecoai.capitalhubapp.com logueado, aparece el prompt 'Activar notificaciones?' a los 3s, aceptar, verificar en Supabase > push_subscriptions que aparece 1 row con el endpoint.\n7. Instalar PWA: en Chrome desktop, barra URL > icono 'Instalar app'. En iPhone Safari, Compartir > Anadir a pantalla de inicio. Verificar que el icono CH monogram aparece correcto.\n\nNotas:\n- Logo CH monogram + favicons + manifest + service worker ya estan commiteados (commit 078ed71).\n- API routes /api/notifications/subscribe y /api/notifications/send ya existen.\n- Para enviar una notificacion manualmente: POST a /api/notifications/send con header Authorization: Bearer <SUPABASE_SERVICE_ROLE_KEY> y body { userId, notification: { title, body, data: { url } } }.",
    status: "next",
    priority: "high",
    assignee: "marco",
    paraId: "a4",
    dueDate: null,
    createdAt: "2026-04-11T13:00:00Z",
    completedAt: null,
  },
]
