import type { Task, ParaItem } from "../types/task"

export const defaultParaItems: ParaItem[] = [
  // Projects
  { id: "p1", name: "Funnel LT8", type: "project" },
  { id: "p2", name: "Funnel Hub + Newsletter", type: "project" },
  { id: "p3", name: "VSL", type: "project" },
  // Areas
  { id: "a1", name: "Marketing", type: "area" },
  { id: "a2", name: "Ventas", type: "area" },
  { id: "a3", name: "Producto", type: "area" },
  { id: "a4", name: "Operaciones", type: "area" },
  // Resources
  { id: "r1", name: "Brandkit", type: "resource" },
  { id: "r2", name: "SOPs", type: "resource" },
]

export const defaultTasks: Task[] = [
  // === COMPLETADAS ===
  {
    id: "t1",
    title: "Anadir seccion de claridad en la landing (que la persona entienda el flow completo)",
    description: "Que el visitante entienda claramente el flujo completo del producto.",
    status: "done",
    priority: "urgent",
    assignee: "marco",
    paraId: "p1",
    dueDate: "2026-04-10",
    createdAt: "2026-04-10T08:00:00Z",
    completedAt: "2026-04-11T10:00:00Z",
  },
  {
    id: "t2",
    title: "Anadir seccion de cinturones/niveles (estilo teaser, que genere curiosidad)",
    description: "Seccion visual tipo gamificacion con niveles/cinturones para generar curiosidad.",
    status: "done",
    priority: "urgent",
    assignee: "marco",
    paraId: "p1",
    dueDate: "2026-04-10",
    createdAt: "2026-04-10T08:05:00Z",
    completedAt: "2026-04-11T10:00:00Z",
  },
  {
    id: "t4",
    title: "Montar Funnel Hub + Newsletter",
    description: "Crear el funnel de captacion con hub de contenido y sistema de newsletter.",
    status: "done",
    priority: "high",
    assignee: "marco",
    paraId: "p2",
    dueDate: "2026-04-13",
    createdAt: "2026-04-10T08:15:00Z",
    completedAt: "2026-04-11T10:00:00Z",
  },
  // === ACTIVAS ===
  {
    id: "t3",
    title: "Esperar 3 dias para metricas solidas de la VSL en PandaVideo",
    description: "Esperar a tener datos suficientes antes de tomar decisiones sobre la VSL.",
    status: "waiting",
    priority: "high",
    assignee: "equipo",
    paraId: "p3",
    dueDate: "2026-04-13",
    createdAt: "2026-04-10T08:10:00Z",
    completedAt: null,
  },
  {
    id: "t5",
    title: "Nuevos anuncios con el enfoque de JP (analisis + formacion + empleo)",
    description: "Crear nuevas creatividades publicitarias con el angulo de analisis + formacion + empleo.",
    status: "next",
    priority: "normal",
    assignee: "marco",
    paraId: "a1",
    dueDate: "2026-04-17",
    createdAt: "2026-04-10T08:20:00Z",
    completedAt: null,
  },
  {
    id: "t6",
    title: "Si VSL no cumple KPIs -> grabar nueva VSL de 3-4 min",
    description: "Contingencia: si las metricas de la VSL actual no cumplen, grabar una nueva version mas corta.",
    status: "someday",
    priority: "normal",
    assignee: "equipo",
    paraId: "p3",
    dueDate: null,
    createdAt: "2026-04-10T08:25:00Z",
    completedAt: null,
  },
  // === NUEVAS ===
  {
    id: "t7",
    title: "Crear pagina de gracias del Funnel Hub (post-registro formulario)",
    description: "Cuando alguien se registra en el formulario del Funnel Hub, redirigir a una pagina de gracias.",
    status: "done",
    priority: "high",
    assignee: "marco",
    paraId: "p2",
    dueDate: null,
    createdAt: "2026-04-11T10:00:00Z",
    completedAt: "2026-04-11T12:00:00Z",
  },
  {
    id: "t8",
    title: "Crear formulario de Busco Talento Digital",
    description: "Formulario para empresas que buscan contratar talento digital certificado por Capital Hub.",
    status: "next",
    priority: "high",
    assignee: "marco",
    paraId: "p2",
    dueDate: null,
    createdAt: "2026-04-11T10:05:00Z",
    completedAt: null,
  },
  {
    id: "t9",
    title: "Anadir link en seccion Quiero una Carrera Digital — Empezar hoy",
    description: "Conectar el CTA de la seccion con el destino correcto.",
    status: "next",
    priority: "normal",
    assignee: "marco",
    paraId: "p2",
    dueDate: null,
    createdAt: "2026-04-11T10:10:00Z",
    completedAt: null,
  },
  {
    id: "t10",
    title: "Anadir links en footer: terminos, privacidad y login",
    description: "Conectar los links del footer a las paginas correspondientes de terminos de uso, politica de privacidad y login.",
    status: "next",
    priority: "normal",
    assignee: "marco",
    paraId: "p2",
    dueDate: null,
    createdAt: "2026-04-11T10:15:00Z",
    completedAt: null,
  },
  {
    id: "t12",
    title: "Cambiar dominio con Adrian",
    description: "Coordinar con Adrian el cambio de dominio.",
    status: "next",
    priority: "high",
    assignee: "equipo",
    paraId: "p2",
    dueDate: null,
    createdAt: "2026-04-11T12:05:00Z",
    completedAt: null,
  },
  {
    id: "t11",
    title: "Anadir API de conversion al formulario de Funnel Hub y a la automatizacion",
    description: "Integrar la API de conversion (CAPI) tanto en el formulario del Funnel Hub como en la automatizacion asociada.",
    status: "next",
    priority: "high",
    assignee: "marco",
    paraId: "p2",
    dueDate: null,
    createdAt: "2026-04-11T12:00:00Z",
    completedAt: null,
  },
]
